#  Create a new Snapshot, Power On, and Send Email

#Vars and Start Logging

$recipient = "my@self.com"
$smtpserver = "mail.abcdself.com"  
$sender = "vmware-automation@myself.com"  
$subject = "Task - Snapshots for $hosts" 
$header = "The following snapshosts exist on prod*: `n"
$footer = "`n`n" + "This email was generated by the Snapshot Prod Script.  Full Transcript available on task server c:\transcripts\"
$smtp = new-object Net.Mail.SmtpClient($SMTPSERVER)
$scriptName = $MyInvocation.MyCommand.Name
$vcenter  = "vcenter"

Start-Transcript -Path ".\Transcripts\$scriptName-Log-$(get-date -Format yyyyddmm_hhmmtt).log" -NoClobber

# Connect to vcenter
Connect-VIServer $vcenter 
$hosts = Get-VM webprod*

# The meat
foreach ($vm in $hosts){
        Write-Host "Beginning Shutdown on $VM"
        Shutdown-VMGuest $vm -Confirm:$false 
        Sleep 30
        while ( (Get-Vm $VM).Powerstate -eq "PoweredOn" ) {
            Write-Host "$(get-date) $vm...not down yet"
                Start-Sleep -s 10
        }
        Write-host -Foregroundcolor green "Server has shutdown... Continuing with Snap and Powerup"
        New-Snapshot -vm $vm -Name "Scheduled Snapshot" 
        Start-VM $vm
        Write-Host "Finished task Sequence on $vm"
}

$body = $header
$body += Get-Snapshot $hosts | Select VM, Name, Created | Out-String
$body += $footer
$smtp.Send($sender, $recipient, $subject, $body)
